## Random Forest Classifier with Pipeline And Hyperparameter Tuning

In [3]:
import seaborn as sns

In [4]:
df=sns.load_dataset('tips')

In [5]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
from sklearn.model_selection import train_test_split

In [11]:
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [13]:
encoder=LabelEncoder()

In [15]:
df["time"]=encoder.fit_transform(df['time'])

In [17]:
df

     total_bill   tip     sex smoker   day  time  size
0         16.99  1.01  Female     No   Sun     0     2
1         10.34  1.66    Male     No   Sun     0     3
2         21.01  3.50    Male     No   Sun     0     3
3         23.68  3.31    Male     No   Sun     0     2
4         24.59  3.61  Female     No   Sun     0     4
..          ...   ...     ...    ...   ...   ...   ...
239       29.03  5.92    Male     No   Sat     0     3
240       27.18  2.00  Female    Yes   Sat     0     2
241       22.67  2.00    Male    Yes   Sat     0     2
242       17.82  1.75    Male     No   Sat     0     2
243       18.78  3.00  Female     No  Thur     0     2

[244 rows x 7 columns]

In [19]:
df['time'].unique()

array([0, 1])

In [21]:
X=df.drop(labels='time',axis=1)

In [23]:
X

     total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [25]:
## y=df['time']
y=df.time

In [27]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int32

In [29]:
X_train,x_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=42)

In [31]:
std=StandardScaler()

In [31]:
pip install pipeline

Requirement already satisfied: pipeline in c:\users\p4pri\anaconda3\lib\site-packages (0.1.0)Note: you may need to restart the kernel to use updated packages.

In [33]:
from sklearn.pipeline import Pipeline

In [35]:
from sklearn.impute import SimpleImputer  ## Handle missing value
from sklearn.preprocessing import StandardScaler  ## feature scaling
from sklearn.preprocessing  import OneHotEncoder ## categorical to numerical
from sklearn.compose import ColumnTransformer

In [37]:
categorical_cols=['sex','smoker','day']
numerical_cols=['total_bill','tip','size']

In [39]:
##Feature Engineering Automation
## Numerical Pipelines 
num_pipline= Pipeline(
steps=[
     ('imputer',SimpleImputer(strategy='median')),## missing values
    ('scaler',StandardScaler()) ## feature scaling
    
]
)


## Categorical Piplelines

cat_pipline=Pipeline(
    steps=[
         ('imputer',SimpleImputer(strategy='most_frequent')), ## missinf value
        ('onehotencoder',OneHotEncoder())  ## categorical feature to numerical feature
        
    ]
)

In [41]:
preprocessor=ColumnTransformer(
    [
        ('num_pipeline',num_pipline,numerical_cols),
        ('cat_pipeline',cat_pipline,categorical_cols)
    ]
)

In [43]:


 X_train=preprocessor.fit_transform(X_train)

 X_test=preprocessor.fit_transform(x_test)

In [113]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [115]:
## Model Training Automation

models={
    'Random Forest':RandomForestClassifier(),
    'Logistic Regression':LogisticRegression()
    ,'Decision Tree':DecisionTreeClassifier()
}

In [101]:
from sklearn.metrics import accuracy_score

In [ ]:
def evaluate_moel(X_train,y_train,X_test,y_test,models):
    report={}
    for i in range(len(models)):
        model=list(models.values())[i]
        #Train Model
        model.fit(X_train,y_train)


        #Predict Testing Data
        y_test_pred=model.predict(X_test)
        
        #Get R2 scores for  test data
        test_model_score=accuracy_score(y_test,y_test_pred)
        report[list(models.keys())[i]]=test_model_score

    return report

In [117]:
evaluate_moel(X_train,y_train,X_test,y_test,models)

{'Random Forest': 0.9795918367346939,
 'Logistic Regression': 1.0,
 'Decision Tree': 0.9795918367346939}

## ** Random forest **  gives the best result

## Hyperparameter Tuning

In [126]:
classifier=RandomForestClassifier()

In [128]:
para={
    'max_depth':[3,5,10,None],
    'n_estimators':[100,200,300]## Number of decision tree to take
    ,'criterion':['gini','entropy']
    
}

In [130]:
from sklearn.model_selection import RandomizedSearchCV

In [136]:
gridCV=RandomizedSearchCV(classifier,param_distributions=para,verbose=3,cv=5,scoring='accuracy')
gridCV.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.974 total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.923 total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, n_estimators=300;, score=1.000 total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.923 total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.923 total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, n_estimators=300;, score=0.974 total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, n_estimators=300;, score=0.923 total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, n_estimators=300;, score=0.974 total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, n_estimators=300;, score=0.923 total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, n_estimators=300;, score=0.923 total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, n_estimators=300;, score=0.974 total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, n_estimators=300;, score=0.923 total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, n_estimators=300;, score=1.000 total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, n_estimators=300;, score=0.949 total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, n_estimators=300;, score=0.923 total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, n_estimators=100;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, n_estimators=100;, score=0.923 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, n_estimators=100;, score=1.000 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, n_estimators=100;, score=0.923 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, n_estimators=100;, score=0.949 total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=None, n_estimators=100;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=None, n_estimators=100;, score=0.923 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=None, n_estimators=100;, score=1.000 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=None, n_estimators=100;, score=0.949 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=None, n_estimators=100;, score=0.923 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=3, n_estimators=100;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=3, n_estimators=100;, score=0.949 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=3, n_estimators=100;, score=0.974 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=3, n_estimators=100;, score=0.923 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=3, n_estimators=100;, score=0.949 total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, n_estimators=300;, score=0.974 total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, n_estimators=300;, score=0.923 total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, n_estimators=300;, score=0.974 total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, n_estimators=300;, score=0.949 total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, n_estimators=300;, score=0.923 total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=None, n_estimators=200;, score=0.974 total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, n_estimators=200;, score=0.923 total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, n_estimators=200;, score=1.000 total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, n_estimators=200;, score=0.949 total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, n_estimators=200;, score=0.923 total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, n_estimators=100;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, n_estimators=100;, score=0.923 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, n_estimators=100;, score=1.000 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, n_estimators=100;, score=0.949 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, n_estimators=100;, score=0.923 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, n_estimators=100;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, n_estimators=100;, score=0.923 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, n_estimators=100;, score=0.974 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, n_estimators=100;, score=0.923 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, n_estimators=100;, score=0.949 total time=   0.0s

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [3, 5, 10, None],
                                        'n_estimators': [100, 200, 300]},
                   scoring='accuracy', verbose=3)

In [138]:
gridCV.best_params_

{'n_estimators': 300, 'max_depth': 10, 'criterion': 'gini'}

In [140]:
y_pred=gridCV.predict(X_test)

In [142]:
accuracy_score(y_test,y_pred)

0.9795918367346939

In [ ]:
## Random forest regressiorn