In [55]:
import seaborn as sns

In [57]:
df=sns.load_dataset('tips')

In [59]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [61]:
from sklearn.preprocessing import OneHotEncoder

In [63]:
df1=OneHotEncoder()

In [65]:
df1

OneHotEncoder()

In [67]:
df3=df1.fit_transform(df[['day','sex','smoker']]).toarray()

In [69]:
import pandas as pd

In [71]:
X=pd.DataFrame(df3,columns=df1.get_feature_names_out())

In [73]:
X

,day_Fri,day_Sat,day_Sun,day_Thur,sex_Female,sex_Male,smoker_No,smoker_Yes
0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
2,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
239,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
240,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
241,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
242,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
243,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0

In [151]:
import numpy as np

In [155]:
k=np.where(df['time'] == 'Dinner', 1, 0)

In [157]:
k

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [159]:
y=pd.DataFrame(k)

In [161]:
y

     0
0    1
1    1
2    1
3    1
4    1
..  ..
239  1
240  1
241  1
242  1
243  1

[244 rows x 1 columns]

In [164]:
from sklearn.model_selection import train_test_split
X_train,x_test,y_train,y_test=train_test_split(X,k,random_state=0,test_size=.2)

In [166]:
from sklearn.naive_bayes import BernoulliNB

In [168]:
nb=BernoulliNB()

In [170]:
nb.fit(X_train,y_train)

BernoulliNB()

In [172]:
y_pred=nb.predict(x_test)

In [174]:
from sklearn.metrics import r2_score,classification_report,accuracy_score,confusion_matrix

In [181]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 9  5]
 [ 1 34]]
0.8775510204081632
              precision    recall  f1-score   support

           0       0.90      0.64      0.75        14
           1       0.87      0.97      0.92        35

    accuracy                           0.88        49
   macro avg       0.89      0.81      0.83        49
weighted avg       0.88      0.88      0.87        49